### ISSUE TITLE
Incorrect position SUNEA SCR 40 - AwningValance (io:AwningValanceIOComponent)

### ISSUE THREAD

**Issue by RualdOrdelman** [iMicknl/ha-tahoma#313]
- [x] **I have read the [Readme](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [Advanced](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section regarding debugging.**

**Describe the bug**
I've a few new Somfy IO screens and the implementation isn't correct. The screen position need to be 100 when opened, but now it's 0.  

Also the UI class isn't correct, but that I can correct myself by customizing the device_class to type "Blind"

We discussed on the HA community forum. 
https://community.home-assistant.io/t/tahoma-integration-refactored/202025/60

**To Reproduce** and  **Screenshots**
See the screenshots on the above link to the community forum

**Environment (please complete the following information):**
- **ha-tahoma version:** [2.3.6]
- **Home Assistant version:** [0.118.3]
- **Platform**: [cover]

**Device:** (if your problem is related to a specific device)

- **Model**/ **Type**: 
ui_class: Awning
widget: AwningValance
controllable_name: 'io:AwningValanceIOComponent'

**Comment by vlebourl** [comment]
As discussed on the forum, the ui_class is correct as it's part of the device info sent by Tahoma, we do not modify it. 
We'll have a look at the position bug.

**Comment by iMicknl** [comment]
@RualdOrdelman I will have a look at this the upcoming days. I will provide you with a test version for this matter.

Could you please share with my the firmware version of your TaHoma box?

**Comment by RualdOrdelman** [comment]
Thanks @iMicknl. Can you tell me how to see the firmware version of my Connexoon box? I didn't see the information in the Somfy Connexoon app or in the HA Integration.

**Comment by iMicknl** [comment]
No clue, but good to know you have the Connexoon 👍🏻. Just trying to grasp when we have to reverse it.

**Comment by iMicknl** [comment]
@RualdOrdelman sorry for the late reply. This should have been fixed in the latest pre-release, which we will release to HACS in the coming week.

**Comment by RualdOrdelman** [comment]
Hi @iMicknl today I did the upgrade to v2.4.0. It looks like the problem is not fixed. 

`current_position: 100
ui_class: ExteriorScreen
widget: PositionableScreen
controllable_name: 'io:VerticalExteriorAwningIOComponent'
rssi_level: 44
'core:NameState': SUNILUS io
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': normal
'core:RSSILevelState': 44
'core:MovingState': false
'core:ClosureState': 0
'core:OpenClosedState': open
'core:Memorized1PositionState': 105
'core:TargetClosureState': 0
friendly_name: Erker links
supported_features: 527
device_class: blind
`

Parameter 'current_position' must be 0 instead of 100.

**Comment by iMicknl** [comment]
@RualdOrdelman in your first post you mentioned:
```
ui_class: Awning
widget: AwningValance
controllable_name: 'io:AwningValanceIOComponent'
```

But in your latest post you mentioned:
```
ui_class: ExteriorScreen 
widget: PositionableScreen 
controllable_name: 'io:VerticalExteriorAwningIOComponent'
```

Could you double check with which devices you encounter these issues? Could you also let me know which hub you have (TaHoma / Connexoon etc) and which firmware.

**Comment by RualdOrdelman** [comment]
Aiiiii sorry I made an mistake. But the conclusion is that the position is wrong. :)

This screen is integrated correctly
`current_position: 100
ui_class: ExteriorScreen
widget: PositionableScreen
controllable_name: 'io:VerticalExteriorAwningIOComponent'
rssi_level: 44
'core:NameState': SUNILUS io
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': normal
'core:RSSILevelState': 44
'core:MovingState': false
'core:ClosureState': 0
'core:OpenClosedState': open
'core:Memorized1PositionState': 105
'core:TargetClosureState': 0
friendly_name: Erker links
supported_features: 527
device_class: blind` 

And this screen is shows the wrong position:
`current_position: 0
ui_class: Awning
widget: AwningValance
controllable_name: 'io:AwningValanceIOComponent'
rssi_level: 64
'core:NameState': SUNEA SCR 40 io
'core:PriorityLockTimerState': 0
'core:StatusState': available
'core:DiscreteRSSILevelState': normal
'core:RSSILevelState': 64
'core:ClosureState': 0
'core:OpenClosedState': open
'core:Memorized1PositionState': 105
friendly_name: Ouderslaapk. links
supported_features: 527
device_class: blind`

**Comment by iMicknl** [comment]
No worries. There have been multiple issues around this topic [(reversed state bugs)](https://github.com/iMicknl/ha-tahoma/labels/bug%3A%20reversed%20state) and unfortunately it is not as simple as just reversing it for your device...

I will follow up when I require more information or when I have a test version.

**Comment by iMicknl** [comment]
Could you give https://github.com/iMicknl/ha-tahoma/archive/fix/awning_valance.zip a try? Extract this file and place `custom_components/tahoma` in your `custom_components` folder. This should solve your issues.

**Comment by RualdOrdelman** [comment]
Great. I've just tested the new files and this solves my problem. What do you recommend to do. Going back to the stable HACS and waiting to get this fix released in a stable version, or just staying at this custom fix version?

**Comment by vlebourl** [comment]
I would stay on this custom version until next release in HACS. If this is merged by then, this will be mentioned in the changelog.

**Comment by RualdOrdelman** [comment]
Would you expect this in the 2.4.7 release?

**Comment by iMicknl** [comment]
> Would you expect this in the 2.4.7 release?

Not sure. It depends a bit on the speed of all the other testers. We had quite some issues with reversed covers and it could be that when we ship this feature, other people will have reversed covers... So we would like to take some time to better understand the behavior on multiple devices / hubs.

**Comment by RualdOrdelman** [comment]
Check. I will keep an eye on that changelog.

Thanks for all your effort.
