### ISSUE TITLE
Can't authenticate with Sauter Cozytouch

### ISSUE THREAD

**Issue by Despotiik** [iMicknl/ha-tahoma#830]
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

Hello,

First of all, I'm quite new to HA and Github so forgive me if I did something wrong in my request or if I get some beginners questions.

I recently bought Sauter Cozytouch bridge so I can get my heaters connected and manageable through app.
I've no issue going through either Sauter Cozytouch app and Atlantic Cozytouch app : I can authenticate, see and manage my heaters, do some schedule, etc.

On HA side, I've downloaded ha-tahoma with HACS. When I click on the Integration button and go to Integration section in order to configure my account, there is no way I can get it working, I always get authentication error.

![image](https://user-images.githubusercontent.com/98315342/202665387-e9364c29-f175-49b6-90dd-69b0b48756e0.png)

I've test few things like manual integration, choose other hub when authenticate, also change my password on Atlantic app to have a "simplier" one but can't figure out why it's not working.

Could you please help me ?
Thanks in advance

### What version of this integration (ha-tahoma) has the issue?

2.14.0

### What version of Home Assistant Core has the issue?

2022.11.2

### Which gateway / hub do you use?

Sauter Cozytouch

### Home Assistant log

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks. The first log line must start with "Added device (Device...".
```

</details>

**Comment by iMicknl** [comment]
Can you try with the Overkiz integration in core? We recently updated this for CozyTouch to show if your hardware is supported, since not all new CozyTouch hardware is supported by Overkiz unfortunately.

**Comment by Despotiik** [comment]
Hey iMicknl

Thanks for your answer.
So I did the following : 

Uninstall on HACS > Reboot > Ensure that ha-tahoma isn't there in custom-components > add Overkiz core integration.
I tried to authenticate with no more success.

Does that mean that my bridge isn't supported ? Is there anything that I can provide/do to maybe help in the future integration ?

**Comment by iMicknl** [comment]
@Despotiik what was the error you received on the Overkiz integration from core?

You could contact me via Discord (iMick #1903) so we can check. Easiest would be if you could temporary change your password and send your credentials, so I can do some live debugging on my machine.

**Comment by fabienmaquin** [comment]
Hi, got same issue over here. (I was on Jeedom before and same problem)

Looks like cozytouch has a server issue or they change their API ?

**Comment by iMicknl** [comment]
@fabienmaquin same reply applies to you, see above. We definitely need more information.

**Comment by fabienmaquin** [comment]
> @fabienmaquin same reply applies to you, see above. We definitely need more information.

Ok would you like my login ? (I will change it after as suggested)

**Comment by Despotiik** [comment]
Just send you request on Discord so I can provide temporary credentials

**Comment by iMicknl** [comment]
@fabienmaquin yes please. The more, the better. And if you can share here which product + hub you own exactly, would be great.

**Comment by mouton-rebelle** [comment]
I had the same issue twice today (incorrect login information) ; every time a reboot fixed it.

**Comment by fabienmaquin** [comment]
@iMicknl sorry for late answer !

My hub: Bridge Cozytouch
My heaters: Pilot interface Cozytouch (x6)
HA version: 2022.11.4

I had a 3 years old account but I created 1 week ago another account and re-paired everything and problem persists...

**Comment by iMicknl** [comment]
Could you contact me on discord as well, @fabienmaquin? I will try to have a look tomorrow.

**Comment by iMicknl** [comment]
I have fixed the issue, but not yet in ha-tahoma. Please try the new beta from core that will be released tomorrow!

Let me know how it works with Overkiz integration from core. (first remove ha-tahoma).

**Comment by fabienmaquin** [comment]
Looks like I still have the issue on my own (last update is done). Just to make sure, login is the same between Atlantic Cozytouch and Sauter Cozitouch ? (I have Sauter one)

**Comment by iMicknl** [comment]
@fabienmaquin which update did you do? You need the public beta 2022.12.b0.

**Comment by fabienmaquin** [comment]
@iMicknl You're right I had the beta update available only this morning. Login is actually working yeah !! Well donne !

I have another issue with an error everytime I try to change a value on radiator (the worst part is that the radiator is well changing its state, but the value on entity keeps on "frost_protection"

Do you want me to do another issue since this one seems to be ok ?

**Comment by iMicknl** [comment]
Please create an issue for this on core, describing your steps / issue and adding your diagnostic information. If it does not work in the beta, it won't be fixed if we don't know.

**Comment by iMicknl** [comment]
Closing this issue here since auth is fixed in Overkiz in core.

**Comment by Despotiik** [comment]
@iMicknl Same here ! I did the update to 2022.12.b0 this morning and authentication is working perfectly through core.
Thanks for your help !
